[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/models/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

# Fallback redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200