[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/models/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.glb"
  [headers.values]
    Content-Type = "model/gltf-binary"
    Access-Control-Allow-Origin = "*"

# Specific handling for GLB files to ensure proper MIME types
[[redirects]]
  from = "/models/character/*.glb"
  to = "/models/character/:splat.glb"
  status = 200
  force = true

# Fallback redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200